ADD = "+"
SUBTRACT = "-"
MULTIPLY = "*"
DIVIDE = "/"
MOD = "%"
DIV = "~"

AND = "&"
OR = "|"
EQUALS = ":"
NOT_EQUALS = "?"
NOT = "!"

END = ";"

DEFINE = "="

COMMENT = "#"

PRINT = "print"

BRACKET_OPEN = "("
BRACKET_CLOSE = ")"


OPERATORS = [ADD, SUBTRACT, MULTIPLY, DIVIDE, MOD, DIV, AND, OR, EQUALS, NOT_EQUALS, NOT, DEFINE, BRACKET_OPEN, BRACKET_CLOSE]
MATH_OPERATORS = [ADD, SUBTRACT, MULTIPLY, DIVIDE, MOD, DIV, AND, OR, EQUALS, NOT]